version: '3'

services:

  influxdb:
    # InfluxDB Docker images: https://hub.docker.com/_/influxdb
    # We are using the InfluxDB 1.x line because it is still the most relevant. InfluxDB 2.x went on to Flux which is
    # now deprecated.
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: playground